django_polling_app/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'django_polling_app.views.home', name='home'),
    # url(r'^django_polling_app/', include('django_polling_app.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    #polling app's url
    url(r'^polls/', include('polls.urls', namespace='polls')),
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
        url(r'^$', views.IndexView.as_view(), name='index'),
        url(r'^(?P<pk>\d+)/', views.DetailView.as_view(), name='details'),
        url(r'^results/(?P<pk>\d+)/$', views.ResultView.as_view(), name='results'),
        url(r'^vote/(?P<poll_id>\d+)$', views.vote, name='vote'),
    )

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
# Create your models here.

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Published Date')
    
    def __unicode__(self):
        return self.question
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date - now
    
class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __unicode__(self):
        return self.choice_text

polls/views.py
# Create your views here.
from django.views import generic
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.core.urlresolvers import reverse

from polls.models import Poll, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'polls_list'
    
    def get_queryset(self):
        return Poll.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    template_name = 'polls/details.html'
    model = Poll
        
class ResultView(generic.DetailView):
    template_name = 'polls/results.html'
    model = Poll
    
def vote(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = Choice.objects.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/details.html', {'poll':poll,'error_msg':'Please select valid choice.'})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(poll.id,)))
        
        
    

polls/templates/polls/detail.html
<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/details.html
<h1>{{ poll.question }}</h1>

{% if error_msg %}
	{{ error_msg }}
{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="post">
	{% csrf_token %}
	{% for choice in poll.choice_set.all %}
    	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
	{% endfor %}
	<input type="submit" value="Vote" />
</form>
<a href="{% url 'polls:index' %}"><< Back to polls.</a>

polls/templates/polls/index.html
<h1>Current Polls</h1>
<ul>
{% for poll in polls_list %}
	<li><a href="{% url 'polls:details' poll.id %}">{{poll.question}}</a></li>
{% endfor %}	
</ul>

polls/templates/polls/results.html
<h1>Result of <i>{{poll.question}}</i></h1>
<table border="1">
<tbody>
<tr><th>Choice</th><th>Votes</th></tr>
{% for choice in poll.choice_set.all %}
	<tr><td>{{choice.choice_text}}</td><td>{{choice.votes}}</td></tr>
{% endfor %}
</tbody>
</table>
<a href="{% url 'polls:index' %}"><< Back to polls.</a>